name: Build, Release & Publish

on:
  push:
    branches:
      - env-for-config

  workflow_dispatch:

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Get tag
        id: get_tag
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Install deps
        run: yarn

      - name: Build plugin
        run: yarn build

      - name: Get Changelog Entry
        id: get_changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.get_tag.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.get_changelog.outputs.changes }}
          tag: ${{ steps.get_changelog.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}        

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}